**ASSIGNMENT 1**

In [2]:
import numpy as np

sampleArray = np.array([[3 ,  6 ,  9 , 12],
                        [15 , 18 , 21 , 24],
                        [27 , 30 , 33 , 36],
                        [39 , 42 , 45 , 48],
                        [51 , 54 , 57 , 60]])

def odd_rows_even_cols(arr):
  return arr[::2, 1::2]

result = odd_rows_even_cols(sampleArray.copy())
print("Printing array of odd rows and even columns")
print(result)

Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


**ASSIGNMENT 2**

In [3]:
import numpy as np

arrayOne = np.array([[5,6,9],[21,18,27]])
arrayTwo = np.array([[15 ,33, 24],[4 ,7, 1]])

result_add = np.add(arrayOne,arrayTwo)

print("addition of two arrays is")
print(result_add)

result_Square = np.square(result_add)

print("\nResult array after calculating the square root of all elements\n")
print(result_Square)


addition of two arrays is
[[20 39 33]
 [25 25 28]]

Result array after calculating the square root of all elements

[[ 400 1521 1089]
 [ 625  625  784]]


**ASSIGNMENT 3**

In [4]:
import numpy as np

sampleArray = np.array([[11, 22, 33],
                        [44, 55, 66],
                        [77, 88, 99]])

def get_third_column(arr):
  return arr[:, 2]  # Select all rows (:) and the third column (index 2)

third_column = get_third_column(sampleArray)

print("Printing array of items in the third column from all rows")
print(third_column)

Printing array of items in the third column from all rows
[33 66 99]


**ASSIGNMENT 4**

In [5]:
import numpy as np

sampleArray = np.array([[3 ,  6 ,  9 , 12],
                        [15 , 18 , 21 , 24],
                        [27 , 30 , 33 , 36],
                        [39 , 42 , 45 , 48],
                        [51 , 54 , 57 , 60]])

def odd_rows_even_cols(arr):
  return arr[::2, 1::2]  # Select elements from odd rows (::2) and even columns (1::2)

result = odd_rows_even_cols(sampleArray.copy())
print("Printing array of odd rows and even columns")
print(result)


Printing array of odd rows and even columns
[[ 6 12]
 [30 36]
 [54 60]]


**ASSIGNMENT 5**

In [6]:
import numpy as np

# Create arrayOne and arrayTwo
arrayOne = np.array([[5, 6, 9], [21, 18, 27]])
arrayTwo = np.array([[15, 33, 24], [4, 7, 1]])

result_add = np.add(arrayOne, arrayTwo)

print("addition of two arrays is\n")
print(result_add)

result_square = np.square(result_add)

print("\nResult array after calculating the square of all elements\n")
print(result_square)

addition of two arrays is

[[20 39 33]
 [25 25 28]]

Result array after calculating the square of all elements

[[ 400 1521 1089]
 [ 625  625  784]]
