**Numpy-**--
Numeric Python
Travis Oliphant in 2005
It is an array processing pkg


**Uses of Numpy Arithmetic operations**

Statistical Operations

Bitwise operators

Copying and viewing arrays

Stacking

Matrix operations

Linear Algebra

Broadcasting

Mathematical operations

Searching,sorting and counting


1 2 3 4----> 1D array indicates 1 row 4 cols

1 2 3
4 5 6
7 8 9  ---->nD    indicates 3 rows and 3 cols

In [ ]:
!pip install numpy


In [ ]:
import numpy as np

In [ ]:
#creating  1D array
x=[1,2,3,4,5]

type(x)

list

*italicized text*

In [ ]:
a=np.array(x)
a
type(a)

numpy.ndarray

In [ ]:
#creating 2D array
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

Methods  On Numpy
1 shape---returns shape of array interns of rows and col


In [ ]:
b.shape

(2, 3)

In [ ]:
#2 .size----returns no elements present in an array
b.size


6

In [ ]:
#Transpose-----It returns an array by swapping rows to col and viz
b.T   #T stands for transpose

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
#ndim---it returns the dimesion of an array
b.ndim

2

In [ ]:
a.ndim

1

In [ ]:
#reshape---It change the shape of an array according to the value mentioned
b.reshape(3,2)


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
a.reshape(5,1)

array([[1],
       [2],
       [3],
       [4],
       [5]])

Functions  in numpy-----
1.Concatinate--It combines a sequence of array with existing array
np.concatinate(arr1,arr2....)
axis =0---row axis
axis=1----col axis

In [ ]:
x=np.array([1,2,3,4,5,6]).reshape(2,3)
x

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
y=np.array([7,8,9,10,11,12]).reshape(2,3)
y

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate((x,y),axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
np.concatenate((x,y),axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
#vstack--This is used to stack seq array vertically...
np.vstack((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#hstack--This is used to stack seq array horizontally...
np.hstack((x,y))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [ ]:
#append ---it used to add  the values to exting array
#np.append(array,values,axis=none)
c=np.array([11,12,13,14,15,16]).reshape(2,3)
c

array([[11, 12, 13],
       [14, 15, 16]])

In [ ]:
np.append(c,[17,18,19]).reshape(3,3)

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [ ]:
np.append(c,y).reshape(4,3)

array([[11, 12, 13],
       [14, 15, 16],
       [ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
#Insert ---adds the value along specified axis
#np.insert(array,index,values,axis=none)
np.insert(c,3,[1,2,3])

array([11, 12, 13,  1,  2,  3, 14, 15, 16])

In [ ]:
#delete--It is used to delete values in specified index
np.delete(c,[1])

array([11, 13, 14, 15, 16])

In [ ]:
#arange--It used to genrate an array with evenly spaced values within a specified interval
#arange(startvalue,endvalue,step)
#by  defaulr start is 0
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,5).reshape(2,2)

array([[1, 2],
       [3, 4]])

In [ ]:
#linespace--It is similar to arange ,but we get evenly spaced  no of specified values whthin specified range
#np.linspace(start,end,num=value)
np.linspace(1,20,10)

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [ ]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#Random.rand--It returns an array of specified shape with random values
np.random.rand(10)

array([0.90345572, 0.56062569, 0.73496987, 0.32177706, 0.81275864,
       0.04027327, 0.06608679, 0.54796668, 0.06223497, 0.87587235])

In [ ]:
np.random.rand(3,3)

array([[0.7727913 , 0.7349382 , 0.91429761],
       [0.65115449, 0.16631646, 0.44881473],
       [0.99532935, 0.4276233 , 0.78433971]])

In [ ]:
np.random.rand(3,2,2)  #(no of matrics,rows,columns)

array([[[0.09291919, 0.25631273],
        [0.10943619, 0.28231204]],

       [[0.9159912 , 0.1807127 ],
        [0.83473306, 0.90519053]],

       [[0.3544605 , 0.7890434 ],
        [0.34637587, 0.77151317]]])

In [ ]:
#Random.randn--It returns an array of specified shape with random values with -ve to +ve
np.random.randn(5)

array([ 0.28056452, -0.24441759,  0.27795841, -0.26771284,  0.59853022])

In [ ]:
np.random.randn(3,4)

array([[ 0.30836183, -0.21351584, -0.06322079,  0.31643161],
       [-0.58452582, -0.9158873 , -0.22006613,  0.9516864 ],
       [ 0.20468022,  1.44834532,  1.02337289,  0.97921203]])

In [ ]:
np.random.randn(2,3,2)

array([[[ 1.43148956,  0.57370554],
        [ 1.42264869, -2.03325056],
        [ 0.31240082,  1.0642734 ]],

       [[-0.83098975, -0.75899323],
        [ 2.30839342, -2.01505625],
        [-0.51327138, -0.06111296]]])

In [ ]:
#slicing and indexing---
#slicing--extracting a set of values from given index position
#Indexing--refers to extracting values from given index position

#index position
a=np.arange(21,31)
a

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
a[2]

23

In [ ]:
a[-2]

29

In [ ]:
a[1:6]

array([22, 23, 24, 25, 26])

In [ ]:
a[:7]

array([21, 22, 23, 24, 25, 26, 27])

In [ ]:
a[5:]

array([26, 27, 28, 29, 30])

In [ ]:
a[:]

array([21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [ ]:
a[::2]

array([21, 23, 25, 27, 29])

In [ ]:
x=np.arange(1,10).reshape(3,3)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x[0,1]  #0---row index    1----col index

2

In [ ]:
x[1,2]

6

In [ ]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
x[1:,1:]    #[row start:row end,col start:col end]

array([[5, 6],
       [8, 9]])

In [ ]:
x[1:,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
x[0:2,1:]

array([[2, 3],
       [5, 6]])

In [ ]:
#Vectorization--- used to perform arithmatic operation each and every element of array

In [ ]:
b=np.arange(1,11)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
b+100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [ ]:
b*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
b/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [ ]:
b>3

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [ ]:
b%2==0

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [ ]:
#masking ---it returns all values>3 insted of returing boolean values
mask=b>3
b[mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [ ]:
b[b%2==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
#selection of values in an array
names=np.array(['ram','sam','jacky','harry','ram'])
names


array(['ram', 'sam', 'jacky', 'harry', 'ram'], dtype='<U5')

In [ ]:
names[names=='ram']

array(['ram', 'ram'], dtype='<U5')

In [ ]:
names[names=='ram1']

array([], dtype='<U5')

In [ ]:
names[names!='sam']

array(['ram', 'jacky', 'harry', 'ram'], dtype='<U5')

In [ ]:
cond1=(names!='ram') #'sam', 'jacky', 'harry'
cond2=(names!='sam')#'ram', 'jacky', 'harry', 'ram']
names[cond1 & cond2]

array(['jacky', 'harry'], dtype='<U5')

In [ ]:
names[cond1 | cond2]

array(['ram', 'sam', 'jacky', 'harry', 'ram'], dtype='<U5')

In [ ]:
np.unique(names)

array(['harry', 'jacky', 'ram', 'sam'], dtype='<U5')

In [ ]:
#Broadcasting

x=np.array([1,3,5])
y=np.array([2,4,6])
print(x)
print(y)
z=x+y
print("the values of z is ",z)

[1 3 5]
[2 4 6]
the values of z is  [ 3  7 11]


In [ ]:
#Fancy index
b=np.zeros((10,10))
b

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.eye(4,5,k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])